version: '3.8'

services:
  character-sheet:
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_USER: cleric
      POSTGRES_PASSWORD: cleric
      POSTGRES_DB: characters
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: